### ISSUE TITLE
Make plugin translatable

### ISSUE THREAD

**Issue by elbnetz** [strangerstudios/pmpro-woocommerce#101]
Vaclav from Poedit wrote:

It seems to me that the only missing bit is actually loading the translations, so adding this to the end of pmpro-woocommerce.php code should help (see the above guide for details):

function my_plugin_load_plugin_textdomain() {
    load_plugin_textdomain( 'pmpro-woocommerce', false, dirname(plugin_basename(__FILE__)) . '/languages/' );
}
add_action( 'plugins_loaded', 'my_plugin_load_plugin_textdomain' );

**Comment by ideadude** [comment]
We had overlooked localization for this add on. The 1.6.1 release has added the code to load the textdomain and updated a few places we were wrapping strings incorrectly.

You can now provide translations on wordpress.org here https://translate.wordpress.org/projects/wp-plugins/pmpro-woocommerce

Once a locale gets 95% coverage, a translation package will be distributed to users of that locale.
