### ISSUE TITLE
Plugin Crashes and cannot use.  Worked fine a few days ago.

### ISSUE THREAD

**Issue by jkrfreshfite** [strangerstudios/pmpro-woocommerce#102]
Fatal error: Can't use method return value in write context in /home4/jkrpto/public_html/wp-content/plugins/pmpro-woocommerce/includes/functions.php on line 25.
Plugin could not be activated because it triggered a fatal error.

Totally crashed my website.  I am back up and running, but cannot use memberships, which isn't acceptable since it's a site where prices are triggered by membership level.

**Comment by andrewlimaza** [comment]
Hi there,

I'm sorry you are experiencing this issue, would you mind telling me what PHP version you are using?

**Comment by eighty20results** [comment]
Using [this link](https://raw.githubusercontent.com/strangerstudios/pmpro-woocommerce/master/includes/functions.php), copy and paste the contents to replace the contents of the `pmpro-woocommerce/includes/functions.php` file in your PMPro/WooCommerce integration add-on.

**Comment by ideadude** [comment]
Should be fixed in 1.6.1. Please open a new issue if you are still having problems. Thanks.
