### ISSUE TITLE
Pmpro-woocommerce isn't granting access to membership after payment 

### ISSUE THREAD

**Issue by Mahutin** [strangerstudios/pmpro-woocommerce#104]
I am using woocommerce checkout as my payment gateway. The main problem is after payment, paid membership pro doesn't grant access to  membership. It shows on woocommerce that order is complete and paid  for, but no membership access is granted.

**Comment by sitzz** [comment]
I have a similar issue. Setting the priority for the add_action call on line 217 of pmpro-woocommerce.php to 1 will solve this particular issue, but it would be better to see what other function hooking into 'woocommerce_order_status_completed' is causing this. That is, however, not an issue of this plugin's author.

The "NOT-A-FIX" fix:
`add_action( 'woocommerce_order_status_completed', 'pmprowoo_add_membership_from_order', 1 );`

However, even with this "fix" it seems there are other issues, as the expiration is not set for memberships. At least that is the case for me.

**Comment by andrewlimaza** [comment]
This should be fixed, cleaning up 'old' Github issues.
