### ISSUE TITLE
membership discount price is not working 

### ISSUE THREAD

**Issue by supermahesh** [strangerstudios/pmpro-woocommerce#105]
Hello I am also having issue
woo-commerce Version 3.4.4
paid membership pro version Version 1.9.5.3
Paid Memberships Pro – Woo-commerce Add On version 1.6.1

I have set three levels sliver, gold and platinum , and i have one simple product A having 5000 regular price , I have set membership prices for sliver 4000 , for gold 3000 and for platinum 2000 but it showing 5000 for all members on product page as well s on cart page

**Comment by ideadude** [comment]
Fixed again here. https://github.com/strangerstudios/pmpro-woocommerce/commit/f78f26e3dc6d316afd28456f4c57aab88b6e7682

This will be in the next release. Thanks.
