### ISSUE TITLE
Paid Memberships Pro & WooCommerce Subscriptions 'On Hold' Status Compatibility Issue

### ISSUE THREAD

**Issue by ninjaval** [strangerstudios/pmpro-woocommerce#106]
It seems like there is no correlated action with Paid Memberships Pro when a WooCommerce Subscription status is set to be 'On-Hold'. I would think that once a Subscription is 'On-Hold' the member would not receive access to member pages. However, nothing appears to happen on the Paid Memberships Pro side in this scenario. Since WooCommerce Subscriptions has the option to 'Manually Renew' subscriptions, this raises a bit of a problem with the compatibility here. If we could have a setting within Paid Memberships Pro to determine how WooCommerce's 'On Hold' statuses are handled in connection with Paid Memberships Pro that would be greatly beneficial!

**Comment by Ojay** [comment]
So three years on and as far as I can tell this still needs resolving. I've just discovered this bug, some 200 subscribers who've been set to "on hold" for various failed payment reasons still have access to our premium content. 

Has there been any development on this over the last three years?? Any settings or what not integrated??

**Comment by JarrydLong** [comment]
Please note that this functionality is available in version 1.7.4 of the Add On.
