### ISSUE TITLE
Feature request: apply the Global Level discount rules to Woo MEMBERSHIP products 

### ISSUE THREAD

**Issue by alexlii1971** [strangerstudios/pmpro-woocommerce#113]
Hello,

If a product on Woocommerce is set as MEMBERSHIP PRODUCT as this screenshot:

http://prntscr.com/moo690

for membership users, the global membership discount rules (as this screenshot: http://prntscr.com/mooalb) will NOT automatically applied to those products.

The Global Level discount rules ONLY works for NON membership product now.

Expected function:
It would be great if there is AN OPTION(Check or Yes/Not)to allow Admin to choose whether globally APPLY the discount rules to Woo MEMBERSHIP PRODUCTS.

Benefits:
We also use BuddyPress Add On, and we want to set all of products as MEMBERSHIP product,  and set a PRODUCT MEMBERSHIP LEVEL in Paid Membership Pro, so that the paid customer will automatically enter a specific group.

Thanks

**Comment by alexlii1971** [comment]
Hello,

We are also use the addon: https://github.com/strangerstudios/pmpro-multiple-memberships-per-user

So totally, we are using these plugins:
pmpro-woocommerce
BuddyPress Add On
pmpro-multiple-memberships-per-user

That means we allow a user can pay for other membership products, and there are no relationships between these Membership products since the Membership products even might be a physical products.

so allow PMPro global discount rules apply to membership products is a much flexible feature.

Thanks.

**Comment by JarrydLong** [comment]
Please navigate to Memberships > Settings > Advanced > and scroll down to 'Apply Member Discounts to WooCommerce Subscription and Membership Products?' You can set the option to Yes or No depending on if you want the discount to be applied or not. 

This functionality is available in 1.7.4. We'll be closing this issue
