### ISSUE TITLE
Request - show notice to remove existing subscription item from cart instead of just not allowing it

### ISSUE THREAD

**Issue by waynep16** [strangerstudios/pmpro-woocommerce#116]
When you have one subscription item in your cart you can't add another. Well, the button doesn't show but that doesn't stop manually adding to cart with query string or shortcode buttons.

As such - if you try to add another subscription item to your cart it is just ignored.

1. the newly added item should automatically remove the old item and put this new one in its place
2. there should be a message asking the user what they want to do

thanks

**Comment by JarrydLong** [comment]
There's functionality available to prevent a member from adding more than one of the same product to the cart. 

Increasing the quantity from the cart page or using the add-to-cart query parameter bypasses this. 

The below code recipe will prevent this from happening and only allow 1 Woo Membership product to be added to the cart

https://gist.github.com/JarrydLong/275d23c0793a38d03a5e9700a00a301b
