### ISSUE TITLE
Issue with pmpro-woocommerce

### ISSUE THREAD

**Issue by irishbaz2** [strangerstudios/pmpro-woocommerce#117]
Keep Getting this message displayed in wordpress when trying to create a subscription service - Warning: Invalid argument supplied for foreach() in /home/systeme3/public_html/wp-content/plugins/pmpro-woocommerce/pmpro-woocommerce.php on line 517. Can't select a type of subscription from he drop down menu,

**Comment by andrewlimaza** [comment]
Due to the age of this issue I am going to close this issue. This should be resolved in the latest version, please open a new issue with steps to replicate this if you are still experiencing this issue.
