### ISSUE TITLE
woocommerce_order_status_on-hold Action typo

### ISSUE THREAD

**Issue by ogiebobogh** [strangerstudios/pmpro-woocommerce#120]
On line 295 of pmp-woocommerce.php there is a typo in the action call:
`add_action( "woocommerce_order_status_on_hold", "pmprowoo_cancel_membership_from_order" );`

Should be: 
`add_action( "woocommerce_order_status_on-hold", "pmprowoo_cancel_membership_from_order" );`

**Comment by andrewlimaza** [comment]
Thanks for bringing this to our attention, this issue has been resolved.
