### ISSUE TITLE
New users

### ISSUE THREAD

**Issue by fabianski7** [strangerstudios/pmpro-woocommerce#124]
When the checkout is finalized by a new customer (who does not have an account) the membership is not assigned to him, even after the payment is approved.
When the user already has an account the plugin is working properly.

Is this bug already known? Any solution?

**Comment by fabianskibr** [comment]
I just tested a similar situation and it worked as it should.

If the product of the purchase is a simple learndash course the access is given correctly after confirmation of payment.

The bug seems to exist only when the product sold is a membership.

**Comment by andrewlimaza** [comment]
Please can you ensure that you do not have guest checkout enabled? This may cause an issue.

If you have any further questions please do not hesitate to reach out to our support team via www.paidmembershipspro.com
