### ISSUE TITLE
Invalid argument supplied for foreach() in pmpro-woocommerce.php on line 517

### ISSUE THREAD

**Issue by pruthuvik** [strangerstudios/pmpro-woocommerce#125]
I did not add any membership levels or anything. Just install this plugin and visit the product edit page.
Snap: https://imgur.com/a/Pe4AANO

**Comment by shadow-lk** [comment]
After installing "Paid Memberships Pro" plugin, the error is fixed. But I think there must be some fallback like "This plugin requires Paid Memberships Pro to work properly" or something like that.

**Comment by andrewlimaza** [comment]
Thanks, this issue has since been fixed.
