### ISSUE TITLE
Original Price not cancelled out when single product sale price is set

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/pmpro-woocommerce#126]
This only adds the strikethrough when the discount is set on the membership level for all products but not Member Discount is set on a single product

https://gist.github.com/andrewlimaza/4ddd2ca1c57951800a8583db347974fd

**Comment by andrewlimaza** [comment]
This issue seems related to the gist and not base functionality of Paid Memberships Pro WooCommerce. Let's discuss this internally and figure out a solution to update this gist if it's not already done.
