### ISSUE TITLE
Product Bundles Support

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/pmpro-woocommerce#127]
https://woocommerce.com/products/product-bundles/

We would need to get a copy of the plugin.

Support the post type. If MMPU is installed, then allow a bundle to give users multiple membership products as part of the bundle.

**Comment by andrewlimaza** [comment]
Some notes about this:

1. User's should use MMPU if the bundle contains more than one product linked to a different membership level.
2. For now, while we look into this further, here is a gist for MMPU & Woo to force multiple levels via Woo checkout - https://gist.github.com/andrewlimaza/27f2d340785a6754b186c5fe99440561

That should fix things temporarily.

**Comment by andrewlimaza** [comment]
Working on this recently, with MMPU being merged into core the gist is all that is needed to give multiple levels to a user -> https://gist.github.com/andrewlimaza/27f2d340785a6754b186c5fe99440561

We already support the post type with membership product meta and works correctly. Adding some notes here in case anyone comes across this:

1.  This gist is needed for multiple membership linked products - https://gist.github.com/andrewlimaza/27f2d340785a6754b186c5fe99440561 (Allows MMPU to run)
2. You can assign a membership level to the product type itself.
3. You can also add membership-products to the bundle.

All levels from point 2 & 3 will be applied (as long as the above filter is set to true). If set to false, the last product processed on order completion will be applied.
