### ISSUE TITLE
PHP error: Warning: A non-numeric value encountered in ....

### ISSUE THREAD

**Issue by maurolangiu** [strangerstudios/pmpro-woocommerce#134]
Hello this is the first time I get this strange issue:

Warning: A non-numeric value encountered in /home/falconfi/public_html/wp-content/plugins/pmpro-woocommerce/pmpro-woocommerce.php on line 660

I did not touch anything on that php file... Could you help me?

**Comment by njsteffey** [comment]
I'm getting the same error (same line and everything)

**Comment by Baggio89** [comment]
same here line 665

**Comment by andrewlimaza** [comment]
This has been fixed and merged in this Pull Request -> https://github.com/strangerstudios/pmpro-woocommerce/pull/153
