### ISSUE TITLE
Not working afte last updates

### ISSUE THREAD

**Issue by xita5200** [strangerstudios/pmpro-woocommerce#135]
Hello,

since the last updates this plugin is not working with learnpress. Users buy membership via woo but can't access courses content

**Comment by andrewlimaza** [comment]
Hi @xita5200 

Are you still experiencing this issue?

I do recommend in reaching out to LearnPress support for further assistance if you haven't managed to resolve this issue. Please note that Github is for bug tracking and not support requests. 

For assistance with troubleshooting an issue, please open a ticket on www.paidmembershipspro.com

I am going to close this issue as it's a support related question. Someone from our team will be able to assist you further once a support ticket is opened.

Thank you for your patience and understanding.
