### ISSUE TITLE
Extend expiration date for members purchasing the same level (renewing).

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-woocommerce#136]
Currently if a member renews their membership through WooCommerce, their expiration date doesn't add the current days remaining to their new subscription and overwrites the enddate with the level's expiration date set.

i.e. Renew a 30 day membership 10 days early should be 40 days expiration on the new period. Users will lose the 10 days.

The 'pmprowoo_checkout_level' also needs more parameters to make it easier to extend.

**Comment by JarrydLong** [comment]
Tested with this in place:
PMPro 2.6.1
Woocommerce 5.6.0
PMPro Woocommerce Add On 1.7.2

The `pmprowoo_checkout_level` filter extends the days as expected in the current version. 

We do however need to make provision for expiration dates that are set to 'hours' (since PMPro 2.6+)

**Comment by andrewlimaza** [comment]
Thanks!
