### ISSUE TITLE
Level Discount applied to membership product on checkout

### ISSUE THREAD

**Issue by dirkbez** [strangerstudios/pmpro-woocommerce#139]
How do I prevent the level discount from being applied to the membership product on checkout?  The discount should only apply after the membership product has been purchased and the user is logged in. 
E.g. Level 1 (discount 10%) -> Woo Product for level 1 Price $10.00.
When a guest user buys the product the checkout amount is $90 i.e. 10% discount has been applied.
This is incorrect as the guest user does not have Level 1 membership yet.

Thanks 
Dirk B.

**Comment by dirkbez** [comment]
Further to this, I assigned the base amount to each of the levels individually on the Woo product, this made no difference.  When a guest checks out o purchasing the membership product, the level discount is applied even though the buyer is still a guest.
In my original example the base price for the Level 1 product should be $100.00 not $10.00

**Comment by dirkbez** [comment]
Further investigation revealed that the level discount is applied to the cart not just the membership product when the guests check out the purchase.  This is incorrect as the level discount should only apply after the membership level was purchased, a guest checkout is not entitled to a membership level discount.

**Comment by kimcoleman** [comment]
Are you using the same product as a membership level product and giving members a discount on the product or are these for different products? The way this currently works is that if the membership product is in the cart at the time of checkout any discounted products in their cart will also be offered at a discount.

I would suggest investigating ways in WooCommerce to force a certain product to be purchased individually with no other products.

**Comment by dirkbez** [comment]
Hi

 

 

I am truly disappointed in your reply, did you even bother to read the full thread on GitHub.

 

Shall I explain it again?

 

When a GUEST purchases a MEMBERSHIP PRODUCT i.e. the WooCommerce Product is the PMPRO membership level and there is a discount assigned to the PMPRO membership level, that discount is applied to the CART.  THIS IS WRONG.  A GUEST is not entitled to any discount until the purchase is complete.

 

Is that simple enough?

 

Your Woocommerce addon is functioning incorrectly.

 

Kind Regards

**Comment by jpaezsa** [comment]
> How do I prevent the level discount from being applied to the membership product on checkout? The discount should only apply after the membership product has been purchased and the user is logged in.
> E.g. Level 1 (discount 10%) -> Woo Product for level 1 Price $10.00.
> When a guest user buys the product the checkout amount is $90 i.e. 10% discount has been applied.
> This is incorrect as the guest user does not have Level 1 membership yet.
> 
> Thanks
> Dirk B.

Bro you find a solution for this? I have the same issue!…
