### ISSUE TITLE
Pricing

### ISSUE THREAD

**Issue by oneillcr** [strangerstudios/pmpro-woocommerce#141]
Membership is logging in and finding items at zero price when should have pricing. Guest prices shown but as soon as logged in for payment prices change to zero.  Contacted WooCommerce; stated this is a plugin compatibility issue. 

No code experience. 
Gone through set up twice to no avail. 

Any help would be appreciated.

**Comment by andrewlimaza** [comment]
Hi @oneillcr 

Thank you for reaching out, please note that Github is used for bug tracking and not support requests (we don't actively crawl Github issues for support).

Please can you open a support ticket on https://www.paidmembershipspro.com or https://wordpress.org/support/plugin/pmpro-woocommerce/

Thank you for understanding, we'll continue to assist you once a support ticket is opened.
