### ISSUE TITLE
Drip-Feed w/ WooCommerce Subscriptions - Each payment resets drip content to day 1.

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-woocommerce#142]
When using Series: Drip-Feed Content with WooCommerce Subscriptions 

Users are making monthly payments for Membership as a product. Each payment resets the users' accounts and the drip-feed content resets.  Members looses all access to drip feed content they previously had.

**Comment by JarrydLong** [comment]
This has been tested using: 

PMPro 2.6.1
Woocommerce 5.6.0
PMPro Series Add On 0.5
PMPro Woocommerce Add On 1.7.2

This issue has already been resolved in a previous release.
