### ISSUE TITLE
Bug: Global Discount is being applied to Membership Level when put in cart / After Advance Settings page is Saved.

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-woocommerce#147]
When not logged in, a user places the Membership Level in their cart, then the level gets the global discount applied to it.

**How to recreate.**
On a new install:
1. Set up the level in PMPro. Add global 10% discount.
2. Create Membership Product for the above level.  Price $100.
3. New user with no account, adds Product to the cart. Cost reads $100. (as it should)
THEN
4. "Save Advance Setting Page" (you don't need to make changes, just save)
5. New user with no account, adds Product to the cart. Now Membership Product reads $90.

**Comment by andrewlimaza** [comment]
Fixed this issue in https://github.com/strangerstudios/pmpro-woocommerce/commit/006956a8c2c382464132e04d2e301646c1a13d85

You can test the 'dev' branch for the latest.
