### ISSUE TITLE
PaidMembershipPro is blocking administrative logins to Wordpress

### ISSUE THREAD

**Issue by dlrueckert** [strangerstudios/pmpro-woocommerce#154]
Has anyone else had a problem with Admin credentials for Wordpress not working when PaidMembershipPro is installed?  It worked fine for a few weeks, but then nobody with admin credentials were able to access the backend of our Wordpress site until we were able to disable PaidMembershipPro.  Is there a setting I can change in PaidMembershipPro, or do I need to find a different membership plugin?

Thanks,
Dan

**Comment by andrewlimaza** [comment]
Hi Dan,

We do not restrict admin access at all but use default WordPress functions to handle login authentication. If your login details stopped working with the default wp-login.php login page this seems that it may be something else interfering.

You may set the login page inside Paid Memberships Pro page settings to "Use WordPress Default" to not use the Paid Memberships Pro login page.

Please note that Github is used for bug tracking and not support. If you need further help with Paid Memberships Pro please consider opening up a support ticket on www.paidmembershipspro.com (as we do not actively crawl Github for support requests).

Thanks for understanding, I hope this helps get you started.
