### ISSUE TITLE
WooCommerce Variable Products support

### ISSUE THREAD

**Issue by DmitryBychenko** [strangerstudios/pmpro-woocommerce#159]
Hello,

Currently PMPro does not support WooCommerce variable products.
Would be nice if PMPro could support it.

I.e.
sell product variation A (product #1111) – get access to Membership level AAAA
sell product variation B (product #2222) – get access to Membership level BBBB
sell product variation C (product #3333) – get access to Membership level CCCC

**Comment by MaryOJob** [comment]
Moderators Only: #455287

Feature request for the ability to also set member pricing for Variable products.

**Comment by andrewlimaza** [comment]
Here is a code recipe you may follow, based off the above gist - https://www.paidmembershipspro.com/set-woocommerce-variable-product-prices-per-membership-level/

**Comment by CJO-code** [comment]
Hi,

I am using the recipe suggested above (https://www.paidmembershipspro.com/set-woocommerce-variable-product-prices-per-membership-level/). This works great for a variable product. 

However, I am also using the YITH Deposits and Down-payments plugin. When a member selects a variable product, the price and deposit are displayed correctly on the product page. When added to the basket however, the prices and totals are incorrect in the basket and the deposit shows as 0 and the full price is immediately payable. Could someone help me please with how to set the correct values with this recipe to allow the deposits and down-payments plugin to work?
