### ISSUE TITLE
Missing argument 2

### ISSUE THREAD

**Issue by dmys** [strangerstudios/pmpro-woocommerce#16]
Hey guys,

I get this error : Warning: Missing argument 2 for pmprowoo_get_membership_price() in /home/www/984df3ba087ba928bad59d6d4782a4c4/web/wp-content/plugins/pmpro-woocommerce/pmpro-woocommerce.php on line 249

Last version of pmpro, woocommerce, and pmpro for woocommerce.

Need help asap please because im running an LMS, and students are waiting.

**Comment by Anime4000** [comment]
I have same issue and ... Wow. error reported since 2014 until now not yet fixed... haha

**Comment by andrewlimaza** [comment]
This should be fixed by now. Please open a new issue if you're still encountering this issue.
