### ISSUE TITLE
When admin manually creates  an order Admin's discount applies rather then Customer

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-woocommerce#165]
When a site owner or admin manually creates an order in the backend the admins discount is applied to the product rather than the customers.

**What should happen:**
When creating a manual order, a customer is selected.  The **customer's** global discount price should appear as the price, not the admins.  This is true if a Member Discount Pricing is set up on a product.

If the customer has a 10% discount and Admin has an 85% discount, the Admin's 85% discount is applied to the order.
<img width="1015" alt="create-order-in-woo" src="https://user-images.githubusercontent.com/8083630/158474089-756481e3-ace9-4244-b5be-84b8deb3dd53.png">

**Comment by leemediagroup** [comment]
Is there anyway we can get an update on this issue? We do have a workaround we are using, but we are trying to integrate with a POS system, and this is creating a bit of a road block for us.

**Comment by andrewlimaza** [comment]
@leemediagroup we are working on figuring this out in the near future.

You can disable this discount by adding the following code to your site:

`function my_remove_discount_manual_order( $discount_price, $level_id, $price, $product ) {
    if ( is_admin() ) {
        return $price;
    }
 }
 add_filter( 'pmprowoo_get_membership_price', 'my_remove_discount_manual_order', 10, 4 );`

**Comment by JarrydLong** [comment]
Tested with Woocommerce 1.7.4 and this is no longer an issue in the latest release
