### ISSUE TITLE
Woocommerce Integration Doesn't Pull Members Details

### ISSUE THREAD

**Issue by itsqjkhan** [strangerstudios/pmpro-woocommerce#181]
I installed the Woocommerce add on to handle the subscription payments, as the payment gateways available in PMP do not work for me. I am facing the following issues:

1- Woocommerce subscription goes smoothly, but the member's list doesn't show those who used Woocommerce payment. 
2- There are some pages that are specific for some membership levels. The use who paid using Woocommerce payments is unable to access the page. He get a message, "This content is for GMM - Monthly, GMM - Quarterly, and GMM Yearly members only." while he already has a membership.

getdigital.ae/gmm is the URL of the test site. 

Please, help.

Thanks

**Comment by andrewlimaza** [comment]
@itsqjkhan Thank you for creating an issue, for support tickets please do not hesitate to open a ticket on our relevant support channel (https://www.paidmembershipspro.com/support) as we don't offer support through Github (as we don't actively check here for support requests and your issue may go unanswered for a while).

However, I'll briefly answer your questions to help you:

1. When selling through WooCommerce, rather look at WooCommerce orders than inside Paid Memberships Pro. We do not create a PMPro order when selling through WooCommerce.
2. This doesn't sound normal and could be a few things interfering here: Their membership level isn't correctly assigned to this account, **[caching](https://www.paidmembershipspro.com/documentation/advanced/caching/)** could be interfering with the dynamic content or you are serving your site over HTTP and HTTPS (switching between the two are separate sessions).

I hope this helps get you started.
