### ISSUE TITLE
Plugin causing massive slowdown at checkout

### ISSUE THREAD

**Issue by chrisio1** [strangerstudios/pmpro-woocommerce#20]
As per the title really!...

If the plugin is enabled and I attempt a purchase the actual checkout screen takes around 60seconds to process the payment.  Disable the plugin and everything is back to normal.

I have tried disabling ALL plugins except the pmpro plugins and woocommerce and the problem is still there.  The only common area is the pmpro-woocommerce.

I am using the latest versions of woocommerce and pmpro.

Thanks

**Comment by andrewlimaza** [comment]
Due to the inactivity and age of this issue I am going to close it and mark it as "resolved" if you are still having this issue please open a support ticket on https://www.paidmembershipspro.com or log any bug/issues in this repository.

Thank you for understanding.
