### ISSUE TITLE
PAP plugin compatible?

### ISSUE THREAD

**Issue by ronoliverclarin** [strangerstudios/pmpro-woocommerce#21]
currently, i am using our addon PAP to PMAP. However, I am thinking to get addon and sell everything in woocommerce. is PAP plugin can fetch the sales tracking even i sent all the products to woocommerce?

**Comment by andrewlimaza** [comment]
Hi yes,

This should work as WooCommerce handles the payments and products. It does not filter the default WooCommerce Checkout process.

Due to the age of this issue I am closing it. If you have any further questions please reach out on www.paidmembershipspro.com support channels.
