### ISSUE TITLE
Membership level not apply price change

### ISSUE THREAD

**Issue by metlock** [strangerstudios/pmpro-woocommerce#25]
Hi been going round in circles for an hour no matter how I configure the product it will only apply the Woo set price not the membership levels:

I have Free and Paid

If free they should see a unit price say £2 if Paid the product should be free. I cant get the member level pricing to apply to the product, what am I doing wrong its like Woo is ignoring the plugin.

**Comment by metlock** [comment]
Not impressed with the Devs months and this bug still exists, they point people to report bugs here and then never fix them. It's impossible to get Membership pricing to work, it wont apply the new price on the store page only ever Free. Tried every combination of settings it wont work. 

Maybe the devs would like to prove me wrong, happy to give access I will even write up a guide for others seeing as this issue is coming up a lot . Just want an answer on behalf of myself and all the others who have reported this problem and not had any answer.

**Comment by andrewlimaza** [comment]
Sorry you ran into this issue, I am going to close this issue as it should have been resolved by now with one of our updates since this issue created and today.

If you have any issues, please feel free to open a support ticket on www.paidmembershipspro.com
