### ISSUE TITLE
Variable Products

### ISSUE THREAD

**Issue by LordThread** [strangerstudios/pmpro-woocommerce#27]
Everything works good but the discount by membership level only shows on the simple product, but don't show on variable product. For example I need to discount a product based on the membership but the product has a small and large price variable need the discount to be applied to each variable to show correct price.

**Comment by Booga-23** [comment]
I have this problem too. Works great on simple product but not on variable products. The discounted price shows in the store when the variation is selected but when you go to the basket it has the undiscounted price.

**Comment by andrewlimaza** [comment]
Here is a solution - https://www.paidmembershipspro.com/set-woocommerce-variable-product-prices-per-membership-level/

Due to the age of this issue, I am closing it. Any further questions regarding the above link may be directed to www.paidmembershipspro.com support channels.
