### ISSUE TITLE
Discounts

### ISSUE THREAD

**Issue by akalex25** [strangerstudios/pmpro-woocommerce#3]
Everything works good but the discount by membership level only shows on the simple product, but don't show on variable product. For example I need to dicount a product based on the membership but the product has a small and large price variable need the discount to be applied to each variable to show correct price.

**Comment by michaelbeil** [comment]
As reported in this [ticket (**moderators only**)](https://contact.paidmembershipspro.com/conversation/27135?folder_id=17):

>I have your plugin installed, everything works great. I have woocommerce, and I set discount percentages for 3 levels I have. I am wondering how I can display on each product page, the percentages that people would save if they chose one of my 3 memebership levels.
>I have found code online that I can show the price minus 10%, but the code does not change when a variable product is chosen. It only shows the cheapest price percentage.
>I would love it if I could display a message under the product "add to cart" button, showing

> "Buy this product for (price minus 10%29 with 1st memebership"
> "Buy this product for (price minus 15%29 with 2nd memebrship"
> "Buy this product for (price minus 25%29 with 3rd membership"
> But it must be dynamic for when people click 9n variable products, and the calculation would calculated their chosen variable.
> 
> I have gotten so far as to show "Buy this product for (price minus 10%29 with 1st membership"
> But I cannot figure out how to dynamically show the price calculation for variable products.
> 
> Is there any way to display what the price of the simple and variable products would be if my customer chose a memebeship level? 

 

**Expected behavior**
The discount by membership level only shows on the simple product, but doesn't show on a variable product.

**Comment by andrewlimaza** [comment]
Here is how you may discount variable products - https://www.paidmembershipspro.com/set-woocommerce-variable-product-prices-per-membership-level/

Due to the age and inactivity on this issue I will close it. If you have further issues please open a ticket on www.paidmembershipspro.com support channels.
