### ISSUE TITLE
payment gateway

### ISSUE THREAD

**Issue by patch84** [strangerstudios/pmpro-woocommerce#32]
I'm looking to make one payment gateway between pmpro and wc.
is it possible to have a plug in the brings wc gateway over to pmpro or the other way round.

also would it be possible to get BACS (Direct Bank Transfer) as a payment option?

many thanks. and great Plug in

**Comment by patch84** [comment]
I see how to add a membership level to wc but I don't see how that sets up a payment schedule?

**Comment by andrewlimaza** [comment]
This should be relayed to the WooCommerce support team on how to setup the payment gateway/payment schedule.

Thank you for understanding.
