### ISSUE TITLE
Login with WC & BBPress

### ISSUE THREAD

**Issue by patch84** [strangerstudios/pmpro-woocommerce#33]
I have set up wc with BBpress so I can have custom fields.

Is it possible to get pmpro to addompt the same login behavior instead of using the admin login page
to have an registration in addition when membership is selected to link to the above.

perhaps my set up seams strange but works great.. I just hope that pmpro can integrate in the same way so that the log in is simplified. I know you already have addons that link these to plugins all be it that they are made to address other useful attributes.

**Comment by andrewlimaza** [comment]
This is now available in Paid Memberships Pro 2.5+
