### ISSUE TITLE
1.3 global discount is not working

### ISSUE THREAD

**Issue by julianruizsa** [strangerstudios/pmpro-woocommerce#43]
The last update is not working with global discount, as the box of "Price for XXX members" is in blank the plug in interpretate that as product is free, so I have to fill this box for every product in the store with the regular price just to apply the discount well...

**Comment by domialex25** [comment]
Having the same issue

**Comment by andrewlimaza** [comment]
You may be able to set the global discount to 100 (for 100% off all products).

@domialex25 Please can you open a support ticket on www.paidmembershipspro.com and someone from our team will assist you further.
