### ISSUE TITLE
Warning: Missing argument 2 for pmprowoo_get_membership_price() in pmpro-woocommerce.php on line 269 in version 1.3.1

### ISSUE THREAD

**Issue by bdennings** [strangerstudios/pmpro-woocommerce#46]
This message appears in every product in the shop after a paid membership is set for a user and will not allow the price to show for the item.  See attached screenshot.
![screen shot 2017-02-06 at 1 26 56 am](https://cloud.githubusercontent.com/assets/20367634/22639559/d6a8cd64-ec0b-11e6-8b18-0731ce41aed1.png)

**Comment by strangerstudios** [comment]
Hmmm. Are you using a beta version of WooCommerce? It seems they are deprecating the woocommerce_get_price filter in the latest on Github and the latest version there might not handle the old filter correctly. Also, let me know what other WC plugins you are using. One of them might make an incorrectly call to add_filters('woocommerce_get_price'...) without the second param.
