### ISSUE TITLE
Improper use of 

### ISSUE THREAD

**Issue by hogash** [strangerstudios/pmpro-woocommerce#52]
Hi @strangerstudios ,

You’ve improperly used the plugins_url function inside \pmpro-woocommerce\pmpro-woocommerce.php when enqueueing the style.

`plugins_url(__FILE__, '/css/style.css' )`

Should be

`plugins_url( '/css/style.css',__FILE__ )`

Thanks!

**Comment by fabiobfava** [comment]
You refers to Line 1 or Line 665?

**Comment by strangerstudios** [comment]
Fixed in the 1.4.2 update pushed out. Please open a new issue if you are still having related problems.

**Comment by strangerstudios** [comment]
p.s. Thanks!
