### ISSUE TITLE
Woocommerce Payment Gateway not Showing on PMPRO Checkout

### ISSUE THREAD

**Issue by travisuche** [strangerstudios/pmpro-woocommerce#57]
Hi!
Please i need your urgent help, I am a PMPro user in Nigeria in Africa and there's no available payment gateway option on pmpro that works in my location and i decided to use woocommerce and its payment gateway for my PMPRO. But the woocommerce payment gateway does not display on checkout nor does it appear on PMPRO payment gateway setup. Is there a possible solution for this to reroute my PMPRO payment gateway fully to my woocommerce gateway setup??? Please help urgently.

Thank you so much. Cheers!

**Comment by andrewlimaza** [comment]
Thanks @travisuche, are you still experiencing this issue?

You are able to sell memberships through WooCommerce using this extension. If you are still experiencing issues, please feel free to open a support request on www.paidmembershipspro.com

Hope this helps! :)

**Comment by eighty20results** [comment]
For posterity:

>  But the woocommerce payment gateway does not display on checkout nor does it appear on PMPRO payment gateway setup.

Adding this add-on (PMPro/WooCommerce integration) doesn't make WooCommerce a payment gateway for Paid Memberships Pro. Instead, it allows you to link Membership Levels to a Product in WooCommerce and sell it through the WooCommerce shopping cart. (Plus a few other capabilities related to the membership level, such as member specific discounts, etc)
