### ISSUE TITLE
Unable to change Autocomplete Order Status

### ISSUE THREAD

**Issue by bagqueen** [strangerstudios/pmpro-woocommerce#58]
Connecting a Woocommerce product to a membership level gives you the option of choosing to autocomplete order status. After choosing the option and saving I'm unable to remove this option.

Adding $autocomplete = 0; at the start of the function pmprowoo_process_product_meta() solves the problem.

**Comment by andrewlimaza** [comment]
This issue has been fixed in an update since this ticket has been posted. Clearing up 'old' issues.
