### ISSUE TITLE
Addon stopped working with WordPress 4.8

### ISSUE THREAD

**Issue by rhurtik** [strangerstudios/pmpro-woocommerce#60]
The icon doesn't show up in Admin panel and the product form throws an error : 
`Warning: Invalid argument supplied for foreach() in /nas/content/staging/scenes4sale/wp-content/plugins/pmpro-woocommerce/pmpro-woocommerce.php on line 385
`
 A similar issue is already reported here => https://wordpress.org/support/topic/addon-stopped-working-with-wordpress-4-8/ .

**Comment by rhurtik** [comment]
The issue was that we have installed Paid Membership Pro - Woocomerce without installing the Paid Membership its self. This should not be allowed by design. Pleas include the WC method 
`is_plugin_active( string $plugin )` 
into your Woocommerce plugin.

**Comment by andrewlimaza** [comment]
Thanks for this @rhurtik, I'm sorry you are experiencing this issue.

I believe that this should be fixed by now, please let me know if you are still experiencing this issue.

**Comment by ideadude** [comment]
Recent updates should have fixed this. Let us know if you're still having related issues.
