### ISSUE TITLE
Cancelling membership in pmpro does not cancel subscription in woocommerce

### ISSUE THREAD

**Issue by jorisberg** [strangerstudios/pmpro-woocommerce#62]
Hi!

I tried to set up pmpro memberships with woocommerce. It became apparent to me that when I buy a subscription product via woocommerce that has a membership attached, the subscription is not cancelled when I click on "cancel membership" in my pmpro account settings.

This is obviously inconvenient as you do not get access anymore but still have to pay..

**Comment by Ojay** [comment]
I've just discovered this too, any fix as yet? I was just doing some last minute testing before rolling out the finished version so it's a good job I found it.

**Comment by andrewlimaza** [comment]
This has been merged in, please open a new support ticket on www.paidmembershipspro.com if this hasn't been resolved.
