### ISSUE TITLE
We are experiencing issues with customer_user

### ISSUE THREAD

**Issue by dantwah** [strangerstudios/pmpro-woocommerce#67]
At this moment we are experiencing issues and receiving errors when trying to pay. It looks like its an issue with PMProWoo. They all start when placing an order. We are at WooCommere 3.2.5

The following issues come up:
PHP message: user_id was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_without_payment, WC_Order->payment_complete, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_changed'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Subscriptions_Order::maybe_record_subscription_payment, WC_Subscription->payment_complete, WC_Subscription->update_status, WC_Order->save, WC_Subscription->status_transition, do_action('woocommerce_subscription_status_changed'), WP_Hook->do_action, WP_Hook->apply_filters, wplms_woo_subscriptions_enable_disable_course_access, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added" while reading response header from upstream, client: IP, server: URL, request: "POST /?wc-ajax=checkout HTTP/1.1", upstream: "fastcgi://unix:/dev/shm/php-fpm.server:", host: "URL", referrer: "PaymentPage"

PHP message: customer_user was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_without_payment, WC_Order->payment_complete, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_changed'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Subscriptions_Order::maybe_record_subscription_payment, WC_Subscription->payment_complete, WC_Subscription->update_status, WC_Order->save, WC_Subscription->status_transition, do_action('woocommerce_subscription_status_active'), WP_Hook->do_action, WP_Hook->apply_filters, pmprowoo_activated_subscription, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0.

2017/12/01 16:00:56 [error] 10104#10104: *252307 FastCGI sent in stderr: "PHP message: order was called incorrectly. Subscription properties should not be accessed directly as WooCommerce 3.0 no longer supports direct property access. Use WC_Subscription::get_parent() instead. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_without_payment, WC_Order->payment_complete, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_changed'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Subscriptions_Order::maybe_record_subscription_payment, WC_Subscription->payment_complete, WC_Subscription->update_status, WC_Order->save, WC_Subscription->status_transition, do_action('woocommerce_subscription_status_active'), WP_Hook->do_action, WP_Hook->apply_filters, pmprowoo_activated_s...

**Comment by andrewlimaza** [comment]
Hi @dantwah 

Thanks for sharing this, I believe this Pull Request should fix this for you - https://github.com/strangerstudios/pmpro-woocommerce/pull/65/files

I hope this helps, please keep me posted.

**Comment by ideadude** [comment]
Fixes have been pulled into master and should be released soon. Let us know if you have related issues still.
