### ISSUE TITLE
bug Issue

### ISSUE THREAD

**Issue by xupeng111** [strangerstudios/pmpro-woocommerce#7]
report an error:Warning: Missing argument 2 for pmprowoo_get_membership_price() in /home/aboutgkc/domains/rtt.teachcg.com/public_html/wp-content/plugins/pmpro-woocommerce/pmpro-woocommerce.php on line 225

**Comment by nonyabusiness** [comment]
This error is still occurring
latest version woocommerce

**Comment by nonyabusiness** [comment]
Warning: Missing argument 2 for pmprowoo_get_membership_price() in *****/wp-content/plugins/pmpro-woocommerce/pmpro-woocommerce.php on line 256

**Comment by edolah** [comment]
Hi there,
I got the same exact message on the page product after installing buddypress plugin. Any idea how to solve that?

**Comment by edolah** [comment]
Anyone??? I'm stuck with it and don't have much alternative: buddypress is required for my site and I need an membership system working with woocommerce... And I like the pmpro manages membership.

**Comment by nonyabusiness** [comment]
Edolah thanks for pointing to buddypress
i can confirm it works without buddypress running hence the conflict is buddypress related
check back with your themes developer
if using the educational related theme suspected this has been fixed now
