### ISSUE TITLE
Warning: A non-numeric value encountered in ... /pmpro-woocommerce/pmpro-woocommerce.php on line 522

### ISSUE THREAD

**Issue by travislima** [strangerstudios/pmpro-woocommerce#70]
Did some digging and this error looks like it comes in the newer version of PHP 7.1 (the user who reported this issue was using 7.1.13). For more information on this please see below:

"New E_WARNING and E_NOTICE errors have been introduced when invalid strings are coerced using operators expecting numbers or their assignment equivalents. An E_NOTICE is emitted when the string begins with a numeric value but contains trailing non-numeric characters, and an E_WARNING is emitted when the string does not contain a numeric value."

**Comment by andrewlimaza** [comment]
Tested this on 7.2 and 7.1.4 and I am unable to recreate this warning/notice.

**Comment by tbnv** [comment]
This issue sill exists (1 year later).

**Comment by AlexaWebhead** [comment]
I have this error too with php 7.2.10 but it's on line 457.

**Comment by andrewlimaza** [comment]
This should be fixed in latest version. If the issue persists, please open a new issue on Github with an updated error.

You may pull a pre-release against the 'dev' branch.
