### ISSUE TITLE
PMPro not setting Membership discount

### ISSUE THREAD

**Issue by travislima** [strangerstudios/pmpro-woocommerce#71]
As per this thread: https://www.paidmembershipspro.com/forums/topic/woo-integration/#post-135545

When doing testing, I was unable to get the membership discount that was applied to the level to work. I set a discount to all Woocommerce products to be 75% off but the regular price still remained.

**Comment by travislima** [comment]
Issue was not working on my end but was working when tested by other developers. Closing topic.

**Comment by andrewlimaza** [comment]
@travislima The issue is the WooCommerce product was set to assign a membership level when bought and this did not discount the product for some reason.

**Comment by domialex25** [comment]
Having the same issue

**Comment by andrewlimaza** [comment]
@domialex25 we do not discount membership products in WooCommerce. You can customize this process if you want to discount membership products.

**Comment by andrewlimaza** [comment]
To add to the above, we do not give membership discount to products that give membership levels in WooCommerce.
