### ISSUE TITLE
Link to Woo Order or Subscription on "Edit Profile" admin page

### ISSUE THREAD

**Issue by greathmaster** [strangerstudios/pmpro-woocommerce#72]
Currently, if a member has checked out with WooCommerce, the "Edit Profile" page correctly shows the member's level, but also says "Not Paying" since it's checking for a payment in PMPro. This creates confusion for some admins, wondering why a particular user is listed as "Not Paying" even though they have orders in WooCommerce.  Linking to the WooCommerce Order or Subscription instead would solve this issue.

It looks like this would require some modifications to the core plugin.

**Comment by andrewlimaza** [comment]
Maybe we could just add a notice that says 'User checked out through WooCommerce, click this link to view their orders'. ?

**Comment by andrewlimaza** [comment]
There's a few ways to do this.

**Comment by andrewlimaza** [comment]
We have removed the "Not Paying" text from the Edit User Profile page.
