### ISSUE TITLE
User doesn`t have access to specific pages after transaction

### ISSUE THREAD

**Issue by tpiekutowski** [strangerstudios/pmpro-woocommerce#79]
Hello,

I`ve got an issue that one of my subscribers bought subscription, but he doesn`t have an access to view restricted pages.

Right after transaction he is logged in on **domain.com/my-account**
When he wants to visit restricted page he has notification that this is only for subscribers. I set the link to redirect users to domain.com/wp-admin on this step, but when he clicks on Login button he is redirected to domain.com/my-account again.

So we tried to logout and then login directly to domain.com/wp-admin
When he logs in on this website he still doesn`t have an access and still has the same notification.

Logging in incognito mode directly to domain.com/wp-admin is working ok and user has an acces. 

How I can solve this issue?

Best,
Tomek

**Comment by ideadude** [comment]
Tomek, did you ever figure this out. It sounds like it might be related to having http and https versions of your site served. Sometimes you log into one but not the other. A good fix is to serve your entire site over https.

It might also be a caching issue. Where the user is logged in, but still seeing the cached version of the page.

**Comment by andrewlimaza** [comment]
Because there have not been any recent updates to this topic, we will be closing the issue.
