### ISSUE TITLE
Filter: Have a filter to adjust discount pricing.

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-woocommerce#82]
We should have a filter inside the function `pmprowoo_get_membership_price` to allow us to filter the price just before we return it.

This will allow developers to exclude products easily from global discount / member discount.

I was looking at something like this ->
`$discount_price = apply_filters( 'pmpro_filter_woo_discount_price', $discount_price, $price, $product );`

**Comment by andrewlimaza** [comment]
I have created a filter and Pull Request here, I think we can name the filter a bit better to be honest -> https://github.com/strangerstudios/pmpro-woocommerce/pull/87

**Comment by andrewlimaza** [comment]
Options discussed:

`pmprowoo_wc_override_discounted_price`
`pmprowoo_override_discounted_wc_price`

**Comment by ideadude** [comment]
We ended up just mirroring the function name: pmprowoo_get_membership_price
