### ISSUE TITLE
CRITICAL Uncaught Error: Call to a member function get_items()

### ISSUE THREAD

**Issue by diguinho2018** [strangerstudios/pmpro-woocommerce#84]
Hello!

I'm doing some tests in my stag website and today I went to WooCommerce my-account page and clicked the cancel subscription button, then after the subscription period I went to check the user's membership level and it was still there. So I went to check the WooCommerce status log to see why the membership level wasn't removed from user and it showed a fatal error as seen bellow.

Plugins:
- PMPro
- PMPro MMPU
- WooCommerce
- WooCommerce Subscriptions
- WooCommerce PayPal Express Checkout

The  WooCommerce Subscription isn't automatically cancelled and is still "Pending Cancellation" under WooCommerce > Subscriptions page.

Reproducing the error:
1. Create PMPro membership level;
2. Create WooCommerce subscription product;
3. Assign membership to product;
4. Pay with paypal express checkout;
5. Accesss WooCommerce my-account page, go to subscriptions and cancel subscription;
5. The scheduled action won't cancel the subscription and will show CRITICAL error.

Could you guys check?

```
2018-05-19T22:58:25+00:00 CRITICAL Uncaught Error: Call to a member function get_items() on integer in /home/webacc/public_html/stag/wp-content/plugins/pmpro-woocommerce/pmpro-woocommerce.php:334
Stack trace:
#0 /home/webacc/public_html/stag/wp-includes/class-wp-hook.php(286): pmprowoo_cancelled_subscription(1690)
#1 /home/webacc/public_html/stag/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /home/webacc/public_html/stag/wp-includes/plugin.php(515): WP_Hook->do_action(Array)
#3 /home/webacc/public_html/stag/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/ActionScheduler_Action.php(22): do_action_ref_array('woocommerce_sch...', Array)
#4 /home/webacc/public_html/stag/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/ActionScheduler_QueueRunner.php(97): ActionScheduler_Action->execute()
#5 /home/webacc/public_html/stag/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/Action
```

**Comment by eighty20results** [comment]
Thank you for the problem report and apologies for the trouble you're having!

I've updated the sources here on GitHub (the update is included in the current 'master' branch). 

You should be able to simply copy/paste the file contents to replace your local `pmpro-woocommerce.php` file with the updated sources.

**Comment by diguinho2018** [comment]
Thank you for your fast reply and update @eighty20results! I'm going to test it out.

**Comment by diguinho2018** [comment]
Hey!
Just tested and it returned the same error @eighty20results.

```
2018-05-21T11:20:17+00:00 CRITICAL Uncaught Error: Call to a member function get_last_order() on integer in /home/webacc/public_html/stag/wp-content/plugins/pmpro-woocommerce/pmpro-woocommerce.php:334
Stack trace:
#0 /home/webacc/public_html/stag/wp-includes/class-wp-hook.php(286): pmprowoo_cancelled_subscription(1892)
#1 /home/webacc/public_html/stag/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /home/webacc/public_html/stag/wp-includes/plugin.php(515): WP_Hook->do_action(Array)
#3 /home/webacc/public_html/stag/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/ActionScheduler_Action.php(22): do_action_ref_array('woocommerce_sch...', Array)
#4 /home/webacc/public_html/stag/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/ActionScheduler_QueueRunner.php(97): ActionScheduler_Action->execute()
#5 /home/webacc/public_html/stag/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/A
```

Double checked and I have the latest `master` files.

**Comment by contemplate** [comment]
Hey @diguinho2018 & @eighty20results we fixed this a month ago b/c of the same issue.  Sometimes $subscription value is just an integer and not the whole object.

In this [PULL](https://github.com/strangerstudios/pmpro-woocommerce/pull/77) (which does other things as well) look at the is_numeric checks. That fixed it for us and order move from Pending Cancel to Cancel just fine.

**Comment by diguinho2018** [comment]
Hey @eighty20results and @contemplate!

I downloaded the latest master and cancelling via admin dashboard is working, the subscription goes from ```Pending Cancel``` to ```Cancelled``` but the membership isn't removed from user. 

Didn't have time to test the subscription scheduled actions to see if it goes from ```Pending Cancel``` to ```Cancelled``` too.

**Comment by ideadude** [comment]
The next release (current master) should have this fixed now. Please open a new issue if you are still having problems.

Thanks!
