### ISSUE TITLE
Multiple Memberships Per User Issue

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-woocommerce#89]
When the PMPro Multiple Memberships Per user is activated it causes issues with WooCommerce Pages.

Issue reference: https://wordpress.org/support/topic/bug-woocommerce-and-pmpro-mmpu-2/

**Comment by eighty20results** [comment]
Already reported here: https://github.com/strangerstudios/pmpro-multiple-memberships-per-user/issues/21

Will close this Issue as I think it belongs in the MMPU issue queue.

**Comment by eighty20results** [comment]
Closing issue as duplicate.
