### ISSUE TITLE
Called to undefined function when cancelling an order.

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-woocommerce#99]
We try to cancel a WooCommerce Subscription when cancelling an order, even when it's not activated.

https://github.com/strangerstudios/pmpro-woocommerce/blob/master/pmpro-woocommerce.php#L258

**Comment by ideadude** [comment]
Fixed here https://github.com/strangerstudios/pmpro-woocommerce/commit/fa8847ddf01850a69b0801bee4db791cd01cf77c
